### ISSUE TITLE
Convert "back" text buttons to icon buttons

### ISSUE THREAD

**Issue by irwiss** [irwiss/astroblaze#43]
Fragments to handle:
- [x] Hiscores
- [x] Options
- [x] Level Complete
- [x] Level Select
- [x] Pilot Change Name

**Comment by andrewshne** [comment]
Options closed in 4a913ec4aed123030316357e8189a99ad04196bf

**Comment by andrewshne** [comment]
Hiscores and Level Complete fragments are closed in da20833a48f5ffa74cdef2c96915d0b2f99bae87

**Comment by andrewshne** [comment]
Level Select closed in 03b8faf4e8b1d919f6b79f41264b79e806b072f6
