### ISSUE TITLE
Film a video presentation

### ISSUE THREAD

**Issue by irwiss** [irwiss/astroblaze#9]
Record the gameplay
Upload to youtube
Do some transitions in a video editor?

**Comment by andrewshne** [comment]
Film sequence suggestion:

- Menu's show case:
1. Show main menu
2. Go to game start
3. Swipe between ships and levels (Stop on best ship and last level)
4. Open shop
5. buy a few upgrades( buy one of the last upgrades to indicate button disabled)

- Game show case:
6. Start game
7. Play for a bit (using missles and lasers for)

- Options show case:
8. Pause game and open options menu
9. In options drop the music in half
10. Drop the UI sound to 0
11. Drop the sounds in half
12. Toggle screen shake (end in off)
13. Toggle vibration (end in off)
14. Toggle flip (end in on)

- Hiscores show case:
15. Back to game play for a bit (less than section 6)
16. Open pause quit to menu
17. Open hiscores

- Ending video
